# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model/User/Entity,Model/Comment/Entity,Model/Mesto/Entity,Model/Adminka/Entity,migrations,Tests,Kernel.php}'

    App\Model\User\Entity\User\UserRepository: ~

    App\Model\Mesto\Entity\Okrugs\OkrugRepository: ~
    App\Model\Mesto\Entity\Okrugs\Oblasts\OblastRepository: ~
    App\Model\Mesto\Entity\Okrugs\Oblasts\Raions\RaionRepository: ~
    App\Model\Mesto\Entity\InfaMesto\MestoNomerRepository: ~

    App\Model\Comment\Entity\Comment\CommentRepository: ~

    App\Model\Adminka\Entity\Uchasties\Group\GroupRepository: ~
    App\Model\Adminka\Entity\Uchasties\Uchastie\UchastieRepository: ~
    App\Model\Adminka\Entity\Uchasties\Personas\PersonaRepository: ~

    App\Model\Adminka\Entity\PcheloMatkas\Kategoria\KategoriaRepository: ~
    App\Model\Adminka\Entity\PcheloMatkas\PcheloMatka\PcheloMatkaRepository: ~

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Finesse\SwiftMailerDefaultsPlugin\SwiftMailerDefaultsPlugin:
        arguments:
            $defaults:
                from:
                    '%env(MAILER_FROM_EMAIL)%': '%env(MAILER_FROM_NAME)%'
        tags:
            - { name: swiftmailer.default.plugin }

    App\Model\User\Service\ResetTokenizer:
        factory: 'App\Container\Model\User\Service\ResetTokenizerFactory:create'
        arguments: ['PT1H']

    Redis:
        class: Redis
        calls:
            -   method: connect
                arguments:
                    - '%env(REDIS_HOST)%'
            -   method: auth
                arguments:
                    - '%env(REDIS_PASSWORD)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    App\Widget\:
        resource: '../src/Widget'
        tags: ['twig.extension']

    App\Menu\SidebarMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: sidebar }]

    App\Menu\Proekts\ProektMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_menu }]

    App\Menu\Adminka\PcheloMainMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: adminka_pchelo_main }]

    App\Menu\Adminka\DrevMainMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: admin_drew_main }]

    App\Menu\Drevos\RodosMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: drevos_rodos }]

    App\Menu\Proekts\PageGlavas\UchastGl\GlavMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_uchast_glav }]

    App\Menu\Proekts\PageGlavas\PcheloMatka\GlavMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_pchelo_glav }]

    App\Menu\Proekts\PageGlavas\PcheloMatka\ChildMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_child_pchelo }]

    App\Menu\Proekts\PageGlavas\BrendMatka\GlavMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_brend_glav }]

    App\Menu\Proekts\PageGlavas\BrendMatka\ChildMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_child_brend }]

    App\Menu\Proekts\PageGlavas\ElitMatka\GlavMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_elit_glav }]

    App\Menu\Proekts\PageGlavas\ElitMatka\ChildMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: proekt_page_child_elit }]

    Symfony\Component\HttpFoundation\Session\Session:
        alias: Symfony\Component\HttpFoundation\Session\SessionInterface

    cebe\markdown\MarkdownExtra:

    App\Service\Adminka\Processor\Driver\:
        resource: '../src/Service/Adminka/Processor/Driver/*Driver.php'
        tags: ['app.twig.adminka_processor.driver']

    App\Service\Adminka\Processor\Processor:
        arguments: [!tagged app.twig.adminka_processor.driver]

#    App\Service\Uploader\FileUploader:
#        arguments: ['@default.storage', '%env(STORAGE_BASE_URL)%']

    App\Model\EventDispatcher:
        class: App\Event\Dispatcher\MessengerEventDispatcher

    phpcent\Client:
        arguments:
            - '%env(CENTRIFUGO_API_HOST)%/api'
            - '%env(CENTRIFUGO_API_KEY)%'
            - '%env(CENTRIFUGO_SECRET)%'
